buildscript {
    ext.kotlin_version = '1.8.22'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://storage.googleapis.com/download.flutter.io" }

        // Allow finding the Unity jar file
        flatDir {
            dirs "${rootDir}/unityLibrary/libs"
        }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// --- MASTER FIX ---
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {

            project.android {

                compileSdkVersion 34

                defaultConfig {
                    minSdkVersion 24
                    targetSdkVersion 34
                }

                if (namespace == null) {
                    if (project.name == "flutter_unity_widget") {
                        namespace "com.xraph.plugin.flutter_unity_widget"
                    }
                }

                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }
            }

            project.tasks.withType(
                org.jetbrains.kotlin.gradle.tasks.KotlinCompile
            ).configureEach {
                kotlinOptions {
                    jvmTarget = "17"
                }
            }
        }
    }
}
// ------------------

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}